### ISSUE TITLE
아카콘 지원

### ISSUE THREAD

**Issue by green1052** [minibox24/DCCon#1]
혹시 아카라이브의 아카콘도 지원해주실 수 있나요?

개인적으로 잘 사용하고 있습니다.

감사합니다

**Comment by minibox24** [comment]
방금까지 구현해보려고 시도하였으나 CORS 문제로 인해서 디스코드 클라이언트에서 (보내기 전 미리보기 용도로) 아카콘 이미지를 불러올 수 없네요..

아쉽습니다

**Comment by green1052** [comment]
> 

혹시 시도하신 코드를 알려주실 수 있나요?

어느 부분에서 CORS가 걸리는건지 궁금하네요
