### ISSUE TITLE
만두 버튼이 안보입니다.

### ISSUE THREAD

**Issue by green1052** [minibox24/DCCon#3]
![image](https://user-images.githubusercontent.com/34261355/162606711-d312b105-5ea4-4fb7-94b3-12a63bbd205d.png)

**Comment by minibox24** [comment]
아까 업데이트를 했는데 아직도 버튼이 나오지 않나요?

**Comment by green1052** [comment]
업데이트가 2번 됐었네요 이제 보입니다.
