### ISSUE TITLE
디씨콘 추가 안 됨

### ISSUE THREAD

**Issue by JadeMin** [minibox24/DCCon#4]
디씨콘 플러그인 설정에서 추가하기 버튼을 누르면 오류나면서 추가가 안 됩니다
![image](https://user-images.githubusercontent.com/36400787/174436155-3e8f0732-a4a5-4359-89de-65de4f7587e5.png)

**Comment by minibox24** [comment]
일단 캡쳐로만 보기에는 request 모듈로 보이는데 다른 플러그인과 충돌한 것은 아닌지 확인 부탁드립니다

**Comment by JadeMin** [comment]
모든 플러그인 비활성화/삭제 후 디스코드 재시작해봤음에도 같은 문제가 발생합니다...
![image](https://user-images.githubusercontent.com/36400787/174444780-f975d0ef-5cec-4ec8-98b0-9741c0629fd7.png)

**Comment by JadeMin** [comment]
해결?했습니다 디스코드 asar 파일의 압축/정리본을 제공하는 OpenAsar 때문이네요 request 모듈단에 문제가 있었나봅니다;;
